apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      containers:
      - name: worker
        image: gcr.io/artisk-photo/worker-service:latest
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
